### Get Rider Coordinates
GET http://localhost:3002/rider-coordinates/rider123

### Post Rider Coordinates
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{
    "lat" : 37.7749, 
    "lng" : -122.4194,
    "rider" : "rider123"
}